name: Make pull
on: [push]
jobs:
  pull:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Make pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: user
          password: ${{ secrets.PASSWORD }}
          port: 666
          script: |
            cd university-nginx
            git reset --hard
            git pull
