name: Update nginx
on:
  workflow_run:
    workflows: ['Make pull']
    types:
      - completed

jobs:
  update-nginx:
    name: Update nginx
    runs-on: ubuntu-latest
    steps:
      - name: Update nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: user
          password: ${{ secrets.PASSWORD }}
          port: 666
          script: |
            echo '${{ secrets.PASSWORD }}' | sudo -S cp ~/university-nginx/nginx.conf /etc/nginx/nginx.conf
            echo '${{ secrets.PASSWORD }}' | sudo -S systemctl reload nginx
